name:                dfa-simulator
version:             0.1.0
github:              "nskins/dfa-simulator"
license:             BSD3
author:              "Nicholas Skinsacos"
maintainer:          "nskins@umich.edu"
copyright:           "2021 Nicholas Skinsacos"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:         Please see the README on GitHub at <https://github.com/nskins/dfa-simulator#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  dfa-simulator-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dfa-simulator

tests:
  dfa-simulator-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dfa-simulator
